//==========[Define Lists of Pokemon by Type]==========//

var bugPokemon = ["caterpie", "metapod", "butterfree", "weedle", "kakuna", "beedrill", "beedrill-mega", "paras", "parasect", "venonat", "venomoth", "scyther", "pinsir", "pinsir-mega", "ledyba", "ledian", "spinarak", "ariados",  "yanma", "pineco", "forretress", "scizor", "scizor-mega", "shuckle", "heracross", "heracross-mega", "wurmple", "silcoon", "beautifly", "cascoon", "dustox", "surskit", "masquerain", "nincada", "ninjask", "shedinja", "volbeat", "illumise", "anorith", "armaldo", "kricketot", "kricketune", "burmy", "wormadam", "mothim", "combee", "vespiqueen", "skorupi", "yanmega", "sewaddle", "leavanny", "venipede", "whirlipede", "scolipede", "dewbble", "crustle", "karrablast", "escavalier", "joltik", "galvantula", "shelmet", "accelgor", "durant", "larvesta", "volcarona", "genesect", "scatterbug", "spewpa", "vivillon", "grubbin", "charjabug", "vikivolt", "cutiefly", "ribombee", "dewpider", "araquanid", "wimpod", "golisopod", "buzzwole", "pheromosa"];

var darkPokemon = ["rattata-alola", "raticate-alola", "meowth-alola", "persian-alola", "grimer-alola", "muk-alola", "gyarados-mega", "umbreon", "murkrow", "sneasel", "houndour", "houndoom", "houndoom-mega", "tyranitar", "tyranitar-mega", "houndoom-mega", "poochyena", "mightyena", "nuzleaf", "shiftry", "sableye", "sableye-mega", "carvanha", "sharpedo", "cacturne", "crawdaunt", "absol", "honchkrow", "stunky", "skuntank", "spiritomb", "drapion", "weavile", "darkrai", "purrloin", "liepard", "sandile", "krokorok", "krookodile", "scraggy", "scrafty", "zorua", "zoroark", "pawniard", "bisharp", "vullaby", "mandibuzz", "deino", "zweilous", "hydreigon", "greninja", "pangoro", "inkay", "malamar", "yveltal", "hoopa", "incineroar", "guzzlord"];

var dragonPokemon = ["charizard-mega-x", "exeggutor-alola", "dratini", "dragonair", "dragonite", "ampharos-mega", "kingdra", "sceptile-mega", "vibrava", "flygon", "altaria", "altaria-mega", "bagon", "shellgon", "salamence", "salamence-mega", "latias", "latias-mega", "latios", "latios-mega", "rayquaza", "rayquaza-mega", "gible", "gabite", "garchomp", "dialga", "palkia", "giratina", "axew", "fraxure", "haxorus", "druddigon", "deino", "zweilous", "hydreigon", "reshiram", "zekrom", "kyurem", "dragalge", "tyrunt", "tyrantrum", "goomy", "sliggoo", "goodra", "noibat", "noivern", "zygarde", "turtonator", "drampa", "jangmo-o", "hakamo-o", "kommo-o", "guzzlord", "necrozma", "naganadel"];

var electricPokemon = ["pikachu", "raichu", "geodude-alola", "graveler-alola", "golem-alola", "magnemite", "magneton", "voltorb", "electrode", "electabuzz", "jolteon", "zapdos", "chinchou", "lanturn", "pichu", "mareep", "flaaffy", "ampharos", "ampharos-mega", "elekid", "raikou", "electrike", "manectric", "manectric-mega", "plusle", "minun", "shinx", "luxio", "luxray", "pachirisu", "magnezone", "electivire", "rotom", "rotom-fan", "rotom-heat", "rotom-wash", "rotom-frost", "rotom-mow", "blitzle", "zebstrika", "emolga", "joltik", "galvantula", "tynamo", "eelektrik", "eelektross", "stunfisk", "thundurus", "zekrom", "helioptile", "heliolisk", "dedenne", "charjabug", "vikavolt", "oricorio", "togedemaru", "tapu koko", "xurkitree", "zeraora"];

var fairyPokemon = ["clefairy", "clefable", "ninetales-alola", "jigglypuff", "wigglytuff", "mr-mime", "cleffa", "igglybuff", "togepi", "togetic", "marill", "azumarill", "snubbull", "granbull", "ralts", "kirlia", "gardevoir", "gardevoir-mega", "azurill", "mawile", "altaria-mega", "mime-jr", "togekiss", "audino-mega", "cottonee", "whimsicott", "flabebe", "floette", "florges", "spritzee", "aromatisse", "swirlix", "slurpuff", "sylveon", "dedenne", "carbink", "klefki", "xerneas", "diancie", "primarina", "cutiefly", "ribombee", "morelull", "shiinotic", "mimikyu", "tapu koko", "tapu lele", "tapu bulu", "tapu fini", "magearna"];

var fightingPokemon = ["mankey", "primeape", "poliwrath", "poliwrath", "machop", "machoke", "machamp", "hitmonlee", "hitmonchan", "mewtwo-mega-x", "heracross-mega", "tyrogue", "hitmontop", "combusken", "blaziken", "breloom", "makuhita", "hariyama", "meditite", "medicham", "monferno", "infernape", "lopunny-mega", "riolu", "lucario", "lucario-mega", "croagunk", "toxicroak", "gallade", "pignite", "emboar", "timburr", "gurdurr", "conkeldurr", "throh", "sawk", "scraggy", "scrafty", "mienfoo", "mienshao", "cobalion", "terrakion", "virizion", "keldeo", "meloetta", "chesnaught", "pancham", "pangoro", "hawlucha", "crabrawler", "crabominable", "stufful", "bewear", "passimian", "hakamo-o", "kommo-o", "buzzwole", "pheromosa", "marshadow"];

var firePokemon = ["charmander", "charmeleon", "charizard", "charizard-mega-y", "charizard-mega-x", "vulpix", "ninetales", "growlithe", "arcanine", "ponyta", "rapidash", "marowak-alola", "magmar", "flareon", "moltres", "cyndaquil", "quilava", "typhlosion", "slugma", "magcargo", "houndour", "houndoom", "houndoom-mega", "magby", "entei", "ho-oh", "torchic", "combusken", "blaziken", "numel", "camerupt", "camerupt-mega", "torkoal", "castform-sunny", "groudon", "chimchar", "monferno", "infernape", "magmortar", "rotom-heat", "heatran", "victini", "tepig", "pignite", "emboar", "pansear", "simisear", "darumaka", "darmanitan", "litwick", "lampent", "chandelure", "heatmor", "larvesta", "volcarona", "reshiram", "fennekin", "braixen", "delphox", "fletchinder", "talonflame", "litleo", "pyroar", "volcanion", "litten", "torracat", "incineroar", "oricorio-baile", "salandit", "salazzle", "turtonator", "blacephalon", "scorbunny"];

var flyingPokemon = ["charizard", "charizard-mega-y", "butterfree", "pidgey", "pidgeotto", "pidgeot", "spearow", "fearow", "zubat", "golbat", "farfetchd", "doduo", "dodrio", "scyther", "pinsir", "gyarados", "aerodactyl", "articuno", "zapdos", "moltres", "dragonite", "hoothoot", "noctowl", "ledyba", "ledian", "crobat", "togetic", "natu", "xatu", "hoppip", "skiploom", "jumpluff", "yanma", "murkrow", "gligar", "delibird", "mantine", "skarmory", "lugia", "ho-oh", "beautifly", "tailow", "swellow", "wingull", "pelipper", "masquerain", "ninjask", "swablu", "altaria", "tropius", "salamence", "salamence-mega", "rayquaza", "rayquaza-mega", "starly", "staravia", "staraptor", "mothim", "combee", "vespiqueen", "drifloon", "drifblim", "honchkrow", "chatot", "mantyke", "togekiss", "yanmega", "gliscor", "rotom-fan", "shaymin", "pidove", "tranquil", "unfezant", "woobat", "swoobat", "sigilyph", "archen", "archeops", "ducklett", "swanna", "emolga", "rufflet", "braviary", "vullaby", "mandibuzz", "tornadus", "thundurus", "landorus", "fletchling", "fletchinder", "talonflame", "vivillon", "hawlucha", "noibat", "noivern", "rowlet", "dartrix", "pikipek", "trumbeak", "toucannon", "oricori-baile", "minior", "celesteela"];

var ghostPokemon = ["gastly", "haunter", "gengar", "marowak-alola", "misdreavus", "shedinja", "sableye", "sableye-mega", "shuppet", "banette", "duskull", "dusclops", "drifblim", "mismagius", "spiritomb", "dusknoir", "froslass", "rotom", "giratina", "yanmask", "cofagrigus", "frillish", "jellicent", "litwick", "lampent", "chandelure", "golett", "golurk", "honedge", "doublade", "aegislash", "phantump", "trevenant", "pumpkaboo", "gourgeist", "hoopa", "decidueye", "oricorio-baile", "sandygast", "palossand", "mimikyu", "dhelmise", "lunala", "necrozma", "marshadow", "blacephalon"];

var grassPokemon = ["bulbasaur", "ivysaur", "venusaur", "venusaur-mega", "oddish", "gloom", "vileplume", "paras", "parasect", "bellsprout", "weepinbell", "victreebel", "exeggcute", "exeggutor", "exeggutor-alola", "tangela", "chikorita", "bayleef", "meganium", "bellossom", "hoppip", "skiploom", "jumpluff", "sunkern", "sunflora", "celebi", "treecko", "grovyle", "sceptile", "sceptile-mega", "lotad", "lombre", "ludicolo", "seedot", "nuzleaf", "shiftry", "shroomish", "breloom", "roselia", "cacnea", "cacturne", "lileep", "cradily", "tropius", "turtwig", "grotle", "torterra", "budew", "roserade", "wormadam", "cherubi", "cherrim", "carnivine", "snover", "abomasnow", "shaymin", "snivy", "servine", "serperior", "pansage", "simisage", "swadloon", "leavanny", "cottonee", "whimsicott", "petilil", "lilligant", "maractus", "deerling", "sawsbuck", "foongus", "amoonguss", "ferroseed", "ferrothorn", "virizion", "chespin", "chesnaught", "skiddo", "gogoat", "phantump", "trevenant", "pumpkaboo", "gourgeist", "rowlet", "dartrix", "decidueye", "fomantis", "lurantis", "morelull", "shiinotic", "bounsweet", "steenee", "tsareena", "dhelmise", "tapu bulu", "kartana", "grookey"];

var groundPokemon = ["sandshrew", "sandslash", "nidoqueen", "nidoking", "diglett", "dugtrio", "geodude", "graveler", "golem", "onix", "cubone", "marowak", "rhyhorn", "rhydon", "wooper", "quagsire", "gligar", "steelix", "swinub", "piloswine", "phanpy", "donphan", "larvitar", "pupitar", "marshtomp", "swampert", "nincada", "numel", "camerupt", "camerupt-mega", "trapinch", "vibrava", "flygon", "barboach", "whiscash", "baltoy", "claydol", "groudon", "torterra", "wormadam", "gastrodon", "gible", "gabite", "garchomp", "hippopotas", "hippowdon", "rhyperior", "gliscor", "mamoswine", "drilbur", "excadrill", "palpitoad", "seismitoad", "sandile", "krokorok", "krookodile", "stunfisk", "golett", "golurk", "landorus", "diggersby", "zygarde", "mudbray", "mudsdale", "sandygast", "palossand"];

var icePokemon = ["sandshrew-alola", "sandslash-alola", "vulpix-alola", "ninetales-alola", "dewgong", "cloyster", "jynx", "lapras", "articuno", "sneasel", "swinub", "piloswine", "delibird", "smoochum", "castform-snowy", "snorunt", "glalie", "spheal", "sealeo", "walrein", "regice", "snover", "abomasnow", "weavile", "glaceon", "mamoswine", "froslass", "rotom-frost", "vanillite", "vanillish", "vanilluxe", "cubchoo", "beartic", "cryogonal", "kyurem", "amaura", "aurorus", "bergmite", "avalugg", "crabominable"];

var normalPokemon = ["pidgey", "pidgeotto", "pidgeot", "rattata", "rattata-alola", "raticate", "raticate-alola", "spearow", "fearow", "meowth", "persian", "jigglypuff", "wigglytuff", "farfetchd", "doduo", "dodrio", "lickitung", "chansey", "kangaskhan", "tauros", "ditto", "eevee", "porygon", "snorlax", "sentret", "furret", "hoothoot", "noctowl", "cleffa", "igglybuff", "aipom", "girafarig", "dunsparce", "teddiursa", "ursaring", "porygon2", "stantler", "smeargle", "miltank", "blissey", "zigzagoon", "linoone", "taillow", "swellow", "slakoth", "vigoroth", "slaking", "whismur", "loudred", "exploud", "azurill", "skitty", "delcatty", "spinda", "swablu", "zangoose", "castform", "kecleon", "starly", "staravia", "staraptor", "bidoof", "bibarel", "ambipom", "buneary", "lopunny", "glameow", "purugly", "happiny", "chatot", "munchlax", "lickilicky", "porygon-z", "regigigas", "arceus", "patrat", "watchog", "lillipup", "herdier", "stoutland", "pidove", "tranquill", "unfezant", "audino", "minccino", "cinccino", "deerling", "sawsbuck", "bouffalant", "rufflet", "braviary", "meloetta", "bunnelby", "diggersby", "fletchling", "litleo", "pyroar", "furfrou", "helioptile", "heliolisk", "pikipek", "trumbeak", "toucannon", "yungoos", "gumshoos", "stufful", "bewear", "oranguru", "type-null", "komala", "drampa", "silvally"];

var poisonPokemon = ["bulbasaur", "ivysaur", "venusaur", "weedle", "kakuna", "beedrill", "beedrill-mega", "ekans", "arbok", "nidoran-m", "nidoran-f", "nidorina", "nidorino", "nidoking", "nidoqueen", "zubat", "golbat", "oddish", "gloom", "vileplume", "venonat", "venomoth", "bellsprout", "weepinbell", "victreebel", "tentacool", "tentacruel", "grimer", "muk", "gastly", "haunter", "gengar", "koffing", "weezing", "spinarak", "ariados", "crobat", "qwilfish", "dustox", "roselia", "gulpin", "swalot", "seviper", "budew", "roserade", "stunky", "skuntank", "skorupi", "drapion", "croagunk", "toxicroak", "venipede", "whirlipede", "scolipede", "trubbish", "garbordor", "foongus", "amoonguss", "skrelp", "dragalge", "mareanie", "toxapex", "salandit", "salazzle", "nihilego", "poipole", "naganadel"];

var psychicPokemon = ["raichu-alola", "abra", "kadabra", "alakazam", "slowpoke", "slowbro", "drowzee", "hypno", "exeggcute", "exeggutor", "starmie", "mr-mime", "jynx", "mewtwo","mewtwo-mega-x", "mewtwo-mega-y", "mew", "natu", "xatu", "espeon", "slowking", "unown", "wobbuffet", "girafarig", "smoochum", "lugia", "celebi", "ralts", "kirlia", "gardevoir", "meditite", "medicham", "spoink", "grumpig", "lunatone", "solrock", "baltoy", "claydol", "chimeco", "wynaut", "beldum", "metang", "metagross", "latias", "latios", "jirachi", "deoxys", "chingling", "bronzor", "bronzong", "mime-jr", "gallade", "uxie", "mesprit", "azelf", "cresselia", "victini", "munna", "musharna", "woobat", "swoobat", "darmanitan", "sigilyph", "gothita", "gothorita", "gothitelle", "solosis", "duosion", "reuniclus", "elgyem", "beheeyem", "meloetta", "delphox", "espurr", "meowstic", "inkay", "malamar", "hoopa", "oricorio-baile", "oranguru", "bruxish", "tapu-lele", "cosmog", "cosmoem", "solgaleo", "lunala", "necrozma"];

var rockPokemon = ["geodude", "geodude-alola", "graveler", "graveler-alola", "golem", "golem-alola", "onix", "rhyhorn", "rhydon", "omanyte", "omastar", "kabuto", "kabutops", "aerodactyl", "sudowoodo", "shuckle", "magcargo", "corsola", "larvitar", "pupitar", "tyranitar", "nosepass", "aron", "lairon", "aggron", "lunatone", "solrock", "lileep", "cradily", "anorith", "armaldo", "relicanth", "regirock", "cranidos", "rampardos", "shieldon", "bastiodon", "bonsly", "rhyperior", "probopass", "roggenrola", "boldore", "gigalith", "dwebble", "crustle", "tirtouga", "carracosta", "archen", "acheops", "terrakion", "binacle", "bibaracle", "tyrunt", "tyrantrum", "amaura", "aurorus", "carbink", "minior", "nihilego", "stakataka"];

var steelPokemon = ["sandshrew-alola", "sandslash-alola", "diglett-alola", "dugtrio-alola", "magnemite", "magneton", "forretress", "scizor", "scizor-mega", "steelix", "steelix-mega", "skarmory", "mawile", "mawile-mega", "aron", "lairon", "aggron", "beldum", "metang", "metagross", "registeel", "jirachi", "empoleon", "shieldon", "bastiodon", "wormadam", "bronzor", "bronzong", "lucario", "lucario-mega", "magnezone", "probopass", "dialga", "heatran", "excadrill", "escavalier", "ferroseed", "ferrothorn", "klink", "klang", "klinklang", "pawniard", "bisharp", "durant", "cobalion", "genesect", "honedge", "doublade", "aegislash", "klefki", "togedemaru", "solgaleo", "celesteela", "kartana", "necrozma", "magearna", "stakataka", "meltan", "melmetal"];

var waterPokemon = ["squirtle", "wartortle", "blastoise", "blastoise-mega", "psyduck", "golduck", "poliwag", "poliwhirl", "poliwrath", "tentacool", "tentacruel", "slowpoke", "slowbro", "seel", "dewgong", "shellder", "cloyster", "krabby", "kingler", "horsea", "seadra", "goldeen", "seaking", "staryu", "starmie", "magikarp", "gyarados", "gyarados-mega", "lapras", "vaporeon", "omanyte", "omastar", "kabuto", "kabutops", "totodile", "croconaw", "feraligatr", "chinchou", "lanturn", "marill", "azumarill", "politoed", "wooper", "quagsire", "slowking", "qwilfish", "corsola", "remoraid", "octillery", "mantine", "kingdra", "suicune", "mudkip", "marshtomp", "swampert", "lotad", "lombre", "ludicolo", "wingull", "pelipper", "surskit", "carvanha", "sharpedo", "sharpedo-mega", "wailmer", "wailord", "barboach", "whiscash", "corphish", "crawdaunt", "feebas", "milotic", "castform-rainy", "spheal", "sealeo", "walrein", "clamperl", "huntail", "gorebyss", "relicanth", "luvdisc", "kyogre", "piplup", "prinplup", "empoleon", "bibarel", "buizel", "floatzel", "shellos", "gastrodon", "finneon", "lumineon", "mantyke", "rotom-wash", "palkia", "phione", "manaphy", "oshawott", "dewott", "samurott", "panpour", "simipour", "tympole", "palpitoad", "seismitoad", "basculin", "tirtouga", "carracosta", "ducklett", "swanna", "frillish", "jellicent", "alomomola", "keldeo", "froakie", "frogadier", "greninja", "binacle", "bibaracle", "skrelp", "clauncher", "clawitzer", "volcanion", "popplio", "brionne", "primarina", "wishiwashi", "mareanie", "toxapex", "dewpider", "araquanid", "wimpod", "golisopod", "pyukumuku", "bruxish", "tapu-fini", "sobble"];